Parte 2 do curso Machine Learning: Introdução a classificação com SKLearn da Alura

Transcrição das aulas do instrutor Guilherme Silveira

Nesta parte, trabalharemos como uma outra fonte de dados para nosso projeto.

Nela, encontramos uma tabela com quatro colunas diferentes, e na qual cada item representa um usuário que acessou um determinado site. Neste site, temos três páginas diferentes: a principal (home); a how it works, que explica o funcionamento do site; e contact, para entrar em contato.

Em cada uma dessas três colunas, que são as features, temos 1 ou 0, indicando se um usuário específico acessou essa página ou não, respectivamente. Por enquanto não nos importa saber a ordem de páginas acessada pelo usuário.

Também temos uma quarta coluna (bought) indicando se esse usuário comprou o produto (1) ou não (0).

In [2]:
import pandas as pd

uri = "https://gist.githubusercontent.com/guilhermesilveira/2d2efa37d66b6c84a722ea627a897ced/raw/10968b997d885cbded1c92938c7a9912ba41c615/tracking.csv"
dados = pd.read_csv(uri)

In [3]:
dados.head()

home  how_it_works  contact  bought
0     1             1        0       0
1     1             1        0       0
2     1             1        0       0
3     1             1        0       0
4     1             1        0       0

In [4]:
dados.shape

(99, 4)

In [8]:
mapa = { 
    "home" : "principal",
    "how_it_works" : "como_funciona",
    "contact" : "contato",
    "bought" : "comprou"
}
dados = dados.rename(columns = mapa)

In [9]:
x= dados[["principal","como_funciona","contato"]]
y= dados[["comprou"]]

x.head()

principal  como_funciona  contato
0          1              1        0
1          1              1        0
2          1              1        0
3          1              1        0
4          1              1        0

In [10]:
treino_x = x[:75]
treino_x.shape

(75, 3)

In [11]:
treino_y = y[:75]
teste_x = x[75:]
teste_y = y[75:]

print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

Treinaremos com 75 elementos e testaremos com 24 elementos


In [12]:
teste_y.shape

(24, 1)

In [13]:
treino_y.shape

(75, 1)

In [15]:
from sklearn.svm import LinearSVC
import numpy as np
modelo = LinearSVC()
modelo.fit(treino_x, np.ravel(treino_y))

LinearSVC()

In [16]:
from sklearn.metrics import accuracy_score

previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

A acurácia foi 95.83%


In [17]:
from sklearn.model_selection import train_test_split

treino_x, teste_x, treino_y, teste_y =train_test_split(x, y, test_size = 0.25)
print(treino_x.shape)
print(teste_x.shape)

(74, 3)
(25, 3)


In [18]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos


C:\Users\Resource\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


A acurácia foi 92.00%


C:\Users\Resource\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
return f(*args, **kwargs)

Por isso usamos o **np.ravel(treino_y)** abaixo

In [20]:
modelo.fit(treino_x, np.ravel(treino_y))
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

A acurácia foi 92.00%


In [22]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, random_state = SEED, test_size = 0.25)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, np.ravel(treino_y))
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos
A acurácia foi 96.00%


In [23]:
treino_y.value_counts()

comprou
0          47
1          27
dtype: int64

In [24]:
teste_y.value_counts()

comprou
0          19
1           6
dtype: int64

Se dividirmos 47 por 27 teremos 1,74. Portanto, para cada pessoa que comprou o produto, temos duas que não compraram. Já no teste temos 19 dividido por 6, que totaliza 3,1 - três pessoas que não compraram para cada uma que comprou. 

Isso significa que a separação entre os dados de treino e teste não está proporcional de acordo com as nossas categorias, o que é bastante arriscado. Por exemplo, se treinarmos apenas com pessoas que não compraram o produto, o algorítimo só saberá que pessoas não compram e esse será o seu palpite padrão pois ele nunca aprendeu que usuários de fato compram o produto.

Portanto, é importante que a proporção dos nossos dados seja proporcional. Para isso,, inseriremos mais um argumento na separação de dados (train_test_split): o stratify = y, que irá estratificar os dados proporcionalmente de acordo com y. 

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 20

treino_x, teste_x, treino_y, teste_y = train_test_split(x, np.ravel(y),
                                                         random_state = SEED, test_size = 0.25,
                                                         stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC()
modelo.fit(treino_x, np.ravel(treino_y))
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 74 elementos e testaremos com 25 elementos
A acurácia foi 96.00%


In [35]:
import numpy as np
unique, counts = np.unique(treino_y, return_counts=True)

#print np.asarray((unique, counts)).T

In [36]:
unique

array([0, 1], dtype=int64)

In [37]:
counts

array([49, 25], dtype=int64)

In [41]:
np.asarray((unique, counts)).T

array([[ 0, 49],
       [ 1, 25]], dtype=int64)

In [43]:
unique_tst, counts_tst = np.unique(teste_y, return_counts=True)

In [48]:
np.asarray((unique_tst, counts_tst)).T

array([[ 0, 17],
       [ 1,  8]], dtype=int64)